### ISSUE TITLE
If possible, remove subtrees with pybind11 and googletest

### ISSUE THREAD

**Issue by alexlenail** [fraenkel-lab/pcst_fast#1]
@ludwigschmidt let me know what you think. It seems like googletest is not a pypy package, which warrants keeping it, I think, but pybind11 probably shouldn't be a subtree, in keeping with the modular attitude we're taking here, right? 

Also, would it be possible to write unit tests using googletest or travis?

**Comment by ludwigschmidt** [comment]
Sure, we can remove the pybind11 subtree. I didn't know that you can import it from pypi. It's worth noting though that keeping the subtree makes development easier. When I want to build the python package at the moment, I can just run `make pcst_fast_py`. Then I have the .so file in the local directory and don't have to worry about working in a virtualenv so that `setup.py install` doesn't pollute my global python installation. Another advantage is that we currently have control about the exact version of pybind11 that we want to use.

So if you have a strong preference, feel free to change it. Otherwise we can keep it as it is, I don't see a strong disadvantage of having the subtree.

googletest is similar in that including the package as a subtree makes development easier. Otherwise I'd have to always set up the right paths to a global googletest installation when I check out the repository. By including googletest (and pybind11), anyone can just git clone the repository and is ready to go.

The unit tests are already using googletest for C++ and pytest for python. I haven't set up travis myself before, but it would indeed be nice to have tests run automatically.

**Comment by alexlenail** [comment]
I hadn't thought it through that far. ;)
